config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  
  root to: "tests#index"

  get :signup, to: 'users#new'
  get :login, to: "sessions#new"
  get :logout, to: "sessions#destroy"

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do 
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :test

  validates :body, presence: true
  #validate :validate_answers_count
  
  #private
  #def validate_answers_count
   # errors.add(:base, "answers count is out of range 1..4") unless answers.count.between? 1, 4
  #end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :find_test, only: [:new, :create]
  before_action :find_question, only: [:show, :destroy, :edit, :update]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to test_path(@question.test), status: :see_other
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: "Question is not found"
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    question.persisted? ? 
      "Edit the question of #{question.test.title}" : 
      "Create a new question of #{question.test.title}"
  end
end

app/views/questions/_form.html.erb
<h1><%= question_header(question) %></h1>
<%= form_with model: [test, question] do |form| %>
  <div>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to 'Show', question_path(question) %></td>
  <td><%= link_to 'Edit', edit_question_path(question) %></td>
  <td><%= link_to "Delete", question_path(question), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"} %></td>
</tr>

app/views/questions/edit.html.erb
<%= render "form", question: @question, test: @test %>

app/views/questions/index.html.erb
<h1>Questions of test: <%= @test.title %></h1>
<table>
  <tr>
    <th>Body</th>
    <th colspan="3">Actions</th>
  </tr>
  <%= render @questions %>
</table>

app/views/questions/new.html.erb
<%= render "form", test: @test, question: @question %>

app/views/questions/show.html.erb
<h1>Question of test: <%= @question.test.title %></h1>
<p><%= @question.body %></p>

<h2>Answers</h2>
<%= link_to "New Answer", new_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<ul>
  <li><%= link_to "Destroy", question_path(@question), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"} %></li>
  <li><%= link_to "Edit", edit_question_path(@question) %></li>
  <li><%= link_to "Show proper test", test_path(@question.test)%></li>
</ul>