config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  
  root to: "tests#index"

  get :signup, to: 'users#new'
  get :login, to: "sessions#new"
  get :logout, to: "sessions#destroy"

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do 
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_count_of_question_answers

  private

  def validate_count_of_question_answers
    errors.add(:base, "answers count for this question is out of range 1..4") if question.answers.count > 3
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
  
    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end
  
  def destroy
    @answer.destroy
    redirect_to @answer.question
  end


  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li> 
	<%= answer.body %><br> 
	<%= link_to 'Show', answer_path(answer) %> | 
	<%= link_to 'Edit', edit_answer_path(answer) %> | 
	<%= link_to 'Delete',
							answer_path(answer),
							data: { turbo_method: :delete, 
                      turbo_confirm: 'Are you sure?' } %>
</li>

app/views/answers/_form.html.erb
<%= form_with model: [question, answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit The Answer</h1>

<p> <%= @answer.question.body %> </p>
<%= render "form", question: @question, answer: @answer %>
<%= link_to "Back", question_path(@answer.question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<p> <%= @answer.question.body %> </p>
<%= render "form", question: @question, answer: @answer%>
<%= link_to "Back", question_path(@question) %>

app/views/answers/show.html.erb
<h1>Question</h1>

<p><%= @answer.question.body %></p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', question_path(@answer.question) %>