config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  
  root to: "tests#index"

  get :signup, to: 'users#new'
  get :login, to: "sessions#new"
  get :logout, to: "sessions#destroy"

  resources :users, only: :create
  resources :sessions, only: :create

  resources :tests do 
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
  end

end

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <ul class="nav-list">

    <li><%= link_to "TEST GURU PROJECT", logged_in? ? tests_path : login_path %></li>

    <% unless logged_in? %>
      <li><%= link_to "Sign Up", signup_path %></li>
      <li><%= link_to "Log In", login_path %></li>
    <% end %>

    <% if logged_in? %>
      <li><%= link_to "Log Out", logout_path %></li>
    <% end %>

  </ul>

  <% if logged_in? %>
    <div class="rightNav">Welcome, <b><%= current_user.full_name %></b> Guru</div>
  <% else %>
    <div class="rightNav">Please, sign up or log in</div>
  <% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test Guru" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>

  <%= render "shared/footer" %>
</html>